# .scrutinizer.yml
checks:
  php: true
build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
  services:
    redisgraph:
      image: redislabs/redisgraph:latest
      ports:
        - 6379

  environment:
    docker: true
    php:
      version: 7.4
      pecl_extensions:
        - igbinary
        - redis
  tests:
      -
        command: 'composer run unit-tests'
        coverage:
          file: 'tests/_output/coverage.xml'
          format: 'clover'
filter:
  excluded_paths:
    - "tests/"