# .scrutinizer.yml
checks:
  php: true
build:
  nodes:
    analysis:
      services:
        redisgraph:
          image: redislabs/redisgraph:latest
          ports:
            - 6379
      tests:
        override:
          - php-scrutinizer-run

  environment:
    docker: true
    php:
      version: 7.4
      pecl_extensions:
        - igbinary
        - redis
  tests:
      -
        command: 'composer run unit-tests'
        coverage:
          file: 'tests/_output/coverage.xml'
          format: 'clover'
filter:
  excluded_paths:
    - "tests/"